
title: Your awesome title
subtitle: Your awesome subtitle
description: >- # this means to ignore newlines until "baseurl:"
  This is the demo site for a Jekyll theme version of
  HTML5 UP's sleek, responsive site template Prologue.
author: Your Incredible Name
email: your-email@example.com
avatar: assets/images/avatar.jpg

# You'll want to customize url and baseurl for your own site:
baseurl: "" # the subpath of your site, e.g. /blog
url: "jekyll.dalec.fr" # the base hostname & protocol for your site

remote_theme : chrisbobbe/jekyll-theme-prologue
collections: [sections]
